version: '3.7'

services:
  https-portal:
    image: steveltn/https-portal:1.7.1
    container_name: https-portal
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'wiki.azzu.mydns.jp -> http://dokuwiki-farms'
#      STAGE: 'production'
      STAGE: 'local'
    volumes:
       - type: volume
         source: https-portal
         target: /var/lib/https-portal
 
  dokuwiki-farms:
#    build: ./build
    image: 'azzurri1934/dokuwiki-farms:0.1'
    container_name: dokuwiki-farms
    restart: always
    ports:
      - '80'
    volumes:
      - type: volume
        source: apache2
        target: /etc/apache2
      - type: volume
        source: htdocs
        target: /var/www/localhost/htdocs

volumes:
  https-portal:
  apache2:
  htdocs:
