version: '3'

services:
  https-portal:
    image: steveltn/https-portal:1.7.1
    container_name: https-portal
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'wiki.azzu.mydns.jp -> http://dokuwiki'
      STAGE: 'production'
    volumes:
       - '~/docker/https-portal/volume:/var/lib/https-portal'
 
  dokuwiki:
    build: ./build
    image: 'azzurri1934/dokuwiki:0.1'
    container_name: dokuwiki
    restart: always
    ports:
      - '80'
    volumes:
      - '~/docker/dokuwiki/volume/apache2:/etc/apache2'
      - '~/docker/dokuwiki/volume/htdocs:/var/www/localhost/htdocs'
